### ISSUE TITLE
 thread '<unnamed>' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by sigaloid** [nic-hartley/httpserv#12]
I know this hasn't been updated in two years and it's not meant to be super safe but I figured I'd report this anyway (since it might be used as a starting point for others). Basically, the `.len()` is not bounds-checked and it just assumes the `%`'s are well-placed. This causes a panic.

https://github.com/nic-hartley/httpserv/blob/585c020/src/http.rs#L40

https://github.com/sigaloid/vial/blob/81f11e25179b8b7a5a2b8fc2c1b03d8f4be86b5e/src/util.rs#L28 is how I fixed it.

**Comment by nic-hartley** [comment]
Sorry for the delay! Apparently GH notifications have been going to the wrong email address.

This definitely shouldn't cause a panic. httpserv's default response is to reset the connection or return a 400, not crash entirely. I'll get that fixed today.

That said, the percent decoding also has other potential dealbreakers, e.g. `%2F` returns an error (because I'm only ever decoding URI *components* and / isn't a valid filename character) so this probably isn't a great starting point. There are specific crates intended to do it well which you should probably use instead.

**Comment by nic-hartley** [comment]
Fixed in c6f07b9
